/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as JadwalRouteImport } from './routes/jadwal'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PengumumanRouteImport } from './routes/pengumuman'
import { Route as PrestasiRouteImport } from './routes/prestasi'
import { Route as SambutanRouteImport } from './routes/sambutan'
import { Route as StrukturRouteImport } from './routes/struktur'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const JadwalRoute = JadwalRouteImport.update({
  id: '/jadwal',
  path: '/jadwal',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PengumumanRoute = PengumumanRouteImport.update({
  id: '/pengumuman',
  path: '/pengumuman',
  getParentRoute: () => rootRouteImport,
} as any)
const PrestasiRoute = PrestasiRouteImport.update({
  id: '/prestasi',
  path: '/prestasi',
  getParentRoute: () => rootRouteImport,
} as any)
const SambutanRoute = SambutanRouteImport.update({
  id: '/sambutan',
  path: '/sambutan',
  getParentRoute: () => rootRouteImport,
} as any)
const StrukturRoute = StrukturRouteImport.update({
  id: '/struktur',
  path: '/struktur',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/jadwal': typeof JadwalRoute
  '/kontak': typeof KontakRoute
  '/login': typeof LoginRoute
  '/pengumuman': typeof PengumumanRoute
  '/prestasi': typeof PrestasiRoute
  '/sambutan': typeof SambutanRoute
  '/struktur': typeof StrukturRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/jadwal': typeof JadwalRoute
  '/kontak': typeof KontakRoute
  '/login': typeof LoginRoute
  '/pengumuman': typeof PengumumanRoute
  '/prestasi': typeof PrestasiRoute
  '/sambutan': typeof SambutanRoute
  '/struktur': typeof StrukturRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/galeri': typeof GaleriRoute
  '/jadwal': typeof JadwalRoute
  '/kontak': typeof KontakRoute
  '/login': typeof LoginRoute
  '/pengumuman': typeof PengumumanRoute
  '/prestasi': typeof PrestasiRoute
  '/sambutan': typeof SambutanRoute
  '/struktur': typeof StrukturRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/galeri'
    | '/jadwal'
    | '/kontak'
    | '/login'
    | '/pengumuman'
    | '/prestasi'
    | '/sambutan'
    | '/struktur'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/galeri'
    | '/jadwal'
    | '/kontak'
    | '/login'
    | '/pengumuman'
    | '/prestasi'
    | '/sambutan'
    | '/struktur'
  id:
    | '__root__'
    | '/'
    | '/galeri'
    | '/jadwal'
    | '/kontak'
    | '/login'
    | '/pengumuman'
    | '/prestasi'
    | '/sambutan'
    | '/struktur'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GaleriRoute: typeof GaleriRoute
  JadwalRoute: typeof JadwalRoute
  KontakRoute: typeof KontakRoute
  LoginRoute: typeof LoginRoute
  PengumumanRoute: typeof PengumumanRoute
  PrestasiRoute: typeof PrestasiRoute
  SambutanRoute: typeof SambutanRoute
  StrukturRoute: typeof StrukturRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jadwal': {
      id: '/jadwal'
      path: '/jadwal'
      fullPath: '/jadwal'
      preLoaderRoute: typeof JadwalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengumuman': {
      id: '/pengumuman'
      path: '/pengumuman'
      fullPath: '/pengumuman'
      preLoaderRoute: typeof PengumumanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prestasi': {
      id: '/prestasi'
      path: '/prestasi'
      fullPath: '/prestasi'
      preLoaderRoute: typeof PrestasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sambutan': {
      id: '/sambutan'
      path: '/sambutan'
      fullPath: '/sambutan'
      preLoaderRoute: typeof SambutanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/struktur': {
      id: '/struktur'
      path: '/struktur'
      fullPath: '/struktur'
      preLoaderRoute: typeof StrukturRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GaleriRoute: GaleriRoute,
  JadwalRoute: JadwalRoute,
  KontakRoute: KontakRoute,
  LoginRoute: LoginRoute,
  PengumumanRoute: PengumumanRoute,
  PrestasiRoute: PrestasiRoute,
  SambutanRoute: SambutanRoute,
  StrukturRoute: StrukturRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
